### ISSUE TITLE
LKRG doesn't build for kernel 5.9

### ISSUE THREAD

**Issue by morfikov** [openwall/lkrg#17]
Using the latest git commit on kernel 5.9:

```
# make
make -C /lib/modules/5.9.0-amd64/build M=/var/lib/dkms/lkrg/0.8.1+git20201011/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.9.0-amd64'
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/ksyms/p_resolve_ksym.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/hashing/p_lkrg_fast_hash.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/comm_channel/p_comm_channel.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/integrity_timer/p_integrity_timer.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/kmod/p_kmod.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/database/CPU.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/database/arch/x86/p_x86_metadata.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/database/arch/x86/p_switch_idt/p_switch_idt.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/database/arch/arm64/p_arm64_metadata.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/database/arch/arm/p_arm_metadata.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/database/arch/p_arch_metadata.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/database/JUMP_LABEL/p_arch_jump_label_transform/p_arch_jump_label_transform.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/database/p_database.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/notifiers/p_notifiers.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/self-defense/hiding/p_hiding.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/exploit_detection/p_rb_ed_trees/p_rb_ed_pids/p_rb_ed_pids_tree.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/exploit_detection/syscalls/p_install.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/exploit_detection/syscalls/p_sys_execve/p_sys_execve.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/exploit_detection/syscalls/p_sys_execveat/p_sys_execveat.o
  CC [M]  /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.o
/var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c: In function ‘p_call_usermodehelper_entry’:
/var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c:169:55: error: ‘struct subprocess_info’ has no member named ‘file’
  169 |       if (!strcmp("none",p_subproc->path) && p_subproc->file) {
      |                                                       ^~
make[2]: *** [scripts/Makefile.build:288: /var/lib/dkms/lkrg/0.8.1+git20201011/build/src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.o] Error 1
make[1]: *** [Makefile:1796: /var/lib/dkms/lkrg/0.8.1+git20201011/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.9.0-amd64'
make: *** [Makefile:98: all] Error 2
```
---
```
# cat /proc/version
Linux version 5.9.0-amd64 (morfik@morfikownia) (gcc (Debian 10.2.0-13) 10.2.0, GNU ld (GNU Binutils for Debian) 2.35.1) #1 SMP PREEMPT Mon Oct 12 08:33:00 CEST 2020
```

**Comment by Jacekalex** [comment]
Mee Too xD

`
# root ~> cat /proc/version 
Linux version 5.9.0-g2 (root@domek) (gcc (Gentoo Hardened 9.3.0-r1 p3) 9.3.0, GNU ld (Gentoo 2.33.1 p2) 2.33.1) #2 SMP PREEMPT Tue Oct 13 18:52:22 CEST 2020
`


`# root ~> make
make -C /lib/modules/5.9.0-g2/build M=/ssdtmp/lkrg modules
make[1]: Wejście do katalogu '/ssdtmp/fabryka/kernel/src64/linux-5.9.0-gentoo'
  CC [M]  /ssdtmp/lkrg/src/modules/ksyms/p_resolve_ksym.o
/ssdtmp/lkrg/src/modules/ksyms/p_resolve_ksym.c: In function ‘p_find_isra_name’:
/ssdtmp/lkrg/src/modules/ksyms/p_resolve_ksym.c:29:9: note: byref variable will be forcibly initialized
   29 |    char p_buf2[0x100];
      |         ^~~~~~
/ssdtmp/lkrg/src/modules/ksyms/p_resolve_ksym.c:28:9: note: byref variable will be forcibly initialized
   28 |    char p_buf[0x100];
      |         ^~~~~
/ssdtmp/lkrg/src/modules/ksyms/p_resolve_ksym.c: In function ‘get_kallsyms_address’:
/ssdtmp/lkrg/src/modules/ksyms/p_resolve_ksym.c:83:18: note: byref variable will be forcibly initialized
   83 |    struct kprobe p_kprobe;
      |                  ^~~~~~~~
  CC [M]  /ssdtmp/lkrg/src/modules/hashing/p_lkrg_fast_hash.o
/ssdtmp/lkrg/src/modules/hashing/p_lkrg_fast_hash.c: In function ‘p_lkrg_fast_hash’:
/ssdtmp/lkrg/src/modules/hashing/p_lkrg_fast_hash.c:31:13: note: byref variable will be forcibly initialized
   31 |    uint64_t p_tmp = 0x0;
      |             ^~~~~
  CC [M]  /ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.o
In file included from /ssdtmp/lkrg/src/modules/comm_channel/../../p_lkrg_main.h:235,
                 from /ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c:18:
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c: In function ‘p_lkrg_open_rw’:
/ssdtmp/lkrg/src/modules/comm_channel/../../modules/wrap/p_struct_wrap.h:340:20: note: byref variable will be forcibly initialized
  340 | static inline void p_lkrg_open_rw(void) {
      |                    ^~~~~~~~~~~~~~
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c: In function ‘p_lkrg_close_rw’:
/ssdtmp/lkrg/src/modules/comm_channel/../../modules/wrap/p_struct_wrap.h:349:20: note: byref variable will be forcibly initialized
  349 | static inline void p_lkrg_close_rw(void) {
      |                    ^~~~~~~~~~~~~~~
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c: In function ‘p_sysctl_pcfi_enforce’:
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c:1032:10: note: byref variable will be forcibly initialized
 1032 |    char *p_str[] = {
      |          ^~~~~
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c: In function ‘p_sysctl_umh_enforce’:
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c:911:10: note: byref variable will be forcibly initialized
  911 |    char *p_str[] = {
      |          ^~~~~
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c: In function ‘p_sysctl_pint_enforce’:
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c:483:10: note: byref variable will be forcibly initialized
  483 |    char *p_str[] = {
      |          ^~~~~
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c: In function ‘p_sysctl_pint_validate’:
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c:444:10: note: byref variable will be forcibly initialized
  444 |    char *p_str[] = {
      |          ^~~~~
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c: In function ‘p_sysctl_kint_enforce’:
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c:397:10: note: byref variable will be forcibly initialized
  397 |    char *p_str[] = {
      |          ^~~~~
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c: In function ‘p_sysctl_kint_validate’:
/ssdtmp/lkrg/src/modules/comm_channel/p_comm_channel.c:352:10: note: byref variable will be forcibly initialized
  352 |    char *p_str[] = {
      |          ^~~~~
  CC [M]  /ssdtmp/lkrg/src/modules/integrity_timer/p_integrity_timer.o
/ssdtmp/lkrg/src/modules/integrity_timer/p_integrity_timer.c: In function ‘p_check_integrity’:
/ssdtmp/lkrg/src/modules/integrity_timer/p_integrity_timer.c:157:23: note: byref variable will be forcibly initialized
  157 |    p_module_kobj_mem *p_module_kobj_tmp = NULL;
      |                       ^~~~~~~~~~~~~~~~~
/ssdtmp/lkrg/src/modules/integrity_timer/p_integrity_timer.c:156:23: note: byref variable will be forcibly initialized
  156 |    p_module_list_mem *p_module_list_tmp = NULL;
      |                       ^~~~~~~~~~~~~~~~~
/ssdtmp/lkrg/src/modules/integrity_timer/p_integrity_timer.c:155:17: note: byref variable will be forcibly initialized
  155 |    unsigned int p_module_kobj_nr_tmp; // Count by walk through the list first
      |                 ^~~~~~~~~~~~~~~~~~~~
/ssdtmp/lkrg/src/modules/integrity_timer/p_integrity_timer.c:154:17: note: byref variable will be forcibly initialized
  154 |    unsigned int p_module_list_nr_tmp; // Count by walk through the list first
      |                 ^~~~~~~~~~~~~~~~~~~~
/ssdtmp/lkrg/src/modules/integrity_timer/p_integrity_timer.c:152:15: note: byref variable will be forcibly initialized
  152 |    p_cpu_info p_tmp_cpu_info;
      |               ^~~~~~~~~~~~~~
  CC [M]  /ssdtmp/lkrg/src/modules/kmod/p_kmod.o
  CC [M]  /ssdtmp/lkrg/src/modules/database/CPU.o
  CC [M]  /ssdtmp/lkrg/src/modules/database/arch/x86/p_x86_metadata.o
/ssdtmp/lkrg/src/modules/database/arch/x86/p_x86_metadata.c: In function ‘p_dump_x86_metadata’:
/ssdtmp/lkrg/src/modules/database/arch/x86/p_x86_metadata.c:84:18: note: byref variable will be forcibly initialized
   84 |    unsigned char p_idtr[0xA];
      |                  ^~~~~~
  CC [M]  /ssdtmp/lkrg/src/modules/database/arch/x86/p_switch_idt/p_switch_idt.o
  CC [M]  /ssdtmp/lkrg/src/modules/database/arch/arm64/p_arm64_metadata.o
  CC [M]  /ssdtmp/lkrg/src/modules/database/arch/arm/p_arm_metadata.o
  CC [M]  /ssdtmp/lkrg/src/modules/database/arch/p_arch_metadata.o
  CC [M]  /ssdtmp/lkrg/src/modules/database/JUMP_LABEL/p_arch_jump_label_transform/p_arch_jump_label_transform.o
  CC [M]  /ssdtmp/lkrg/src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.o
  CC [M]  /ssdtmp/lkrg/src/modules/database/p_database.o
  CC [M]  /ssdtmp/lkrg/src/modules/notifiers/p_notifiers.o
  CC [M]  /ssdtmp/lkrg/src/modules/self-defense/hiding/p_hiding.o
  CC [M]  /ssdtmp/lkrg/src/modules/exploit_detection/p_rb_ed_trees/p_rb_ed_pids/p_rb_ed_pids_tree.o
  CC [M]  /ssdtmp/lkrg/src/modules/exploit_detection/syscalls/p_install.o
/ssdtmp/lkrg/src/modules/exploit_detection/syscalls/p_install.c: In function ‘p_install_hook’:
/ssdtmp/lkrg/src/modules/exploit_detection/syscalls/p_install.c:27:27: note: byref variable will be forcibly initialized
   27 |    struct p_isra_argument p_isra_arg;
      |                           ^~~~~~~~~~
  CC [M]  /ssdtmp/lkrg/src/modules/exploit_detection/syscalls/p_sys_execve/p_sys_execve.o
  CC [M]  /ssdtmp/lkrg/src/modules/exploit_detection/syscalls/p_sys_execveat/p_sys_execveat.o
  CC [M]  /ssdtmp/lkrg/src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.o
/ssdtmp/lkrg/src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c: In function ‘p_call_usermodehelper_entry’:
/ssdtmp/lkrg/src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c:169:55: error: ‘struct subprocess_inf ’ has no member named ‘file’
  169 |       if (!strcmp("none",p_subproc->path) && p_subproc->file) {
      |                                                       ^~
make[2]: *** [scripts/Makefile.build:283: /ssdtmp/lkrg/src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.o] Błąd 1
make[1]: *** [Makefile:1784: /ssdtmp/lkrg] Błąd 2
make[1]: Opuszczenie katalogu '/ssdtmp/fabryka/kernel/src64/linux-5.9.0-gentoo'
make: *** [Makefile:98: all] Błąd 2
`

**Comment by 0xC0ncord** [comment]
It seems that `__module_address` and `__module_text_address` syms are no longer exported in 5.9, so that will need reworking too.

**Comment by 0xC0ncord** [comment]
#18 gets LKRG building and running on 5.9.

**Comment by solardiz** [comment]
I've just merged #18 (thanks @0xC0ncord!), which fixes the literal issue described here (build failure), but there's a remaining bit of work on Linux 5.9+ support now tracked as #19.
